version: '3.8'

services:

  mysql-container:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3307:3306"

  ecommerce-app:
    image: ecommerce-app
    container_name: ecommerce-container-v2
    depends_on:
      - mysql-container
    ports:
      - "9090:9090"